services:
  db:
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
  api:
    read_only: true
    tmpfs: [/tmp]
    security_opt: [no-new-privileges:true]
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
  web:
    read_only: true
    tmpfs: [/var/cache/nginx, /var/run]
    security_opt: [no-new-privileges:true]
  gateway:
    read_only: true
    tmpfs: [/var/cache/nginx, /var/run]
    security_opt: [no-new-privileges:true]

